### PR TITLE
Else hunting.

### PR DESCRIPTION
**Pull request by rdohms**
Removed unneeded else and relied on return calls. (According to Object Calisthenics I try to avoid else.)

What do you think about this implementation, does it improve anything? I really wanted to discuss this with someone else and get some opinions.

Discuss.

### CODE REVIEW

**Comment by rdohms** [comment]
My view is:
- reduces complexity
- makes more clear "exit/break points"
- Leaves a more linear outline of function

**Comment by drubb** [comment]
I'm absolutely with you and like the idea of early returns in general. Maybe I'd use a switch statement for even more beauty.

**Comment by debo** [comment]
@rdohms I'm with you too, but I disagree with the switch statement suggestion because it doesn't really add much to this particular case, it would be different in others though; Also I am a bit surprised there wasn't a second else in the previous implementation :-)

**Comment by Jean85** [comment]
I love your talk about Obj. Calisthenics!
(for those who don't know: https://www.youtube.com/watch?v=H2AvoAzbGOE)

I try to apply them too, but I find this case rather interesting, because it highlights a particular opinion of mine: **multiple returns are useful but they should be used with caution**. 

Backstory: I was taught at the university that having more than one return point in your code is a bad thing, it should be one point in, one point out in each function. I later learned, with experience, that that is not always true. In fact, we already have exceptions as additional exit points, and we can assure that we have just one "kind" of exit point enforcing the type of the returned value (hello PHP 7! :heart:).

Also, I now think that this one-in-one-out principle is useful only with imperative and procedural code: with OOP, I always strive to write short methods, so having multiple return points is not an issue, they are clearly visible; it's even good if you are just using them for the "happy path", as @rdohms calls it in his talk.

On the other hand, I don't like to **always** avoid elses, and I think that in this case you made the code more readable because of an other calisthenic rule: you **avoided multiple indentation levels**.

[EDIT] So, at this point, I would prefer a switch too, as I think that it achieves the same purpose, with even more elegance:

```
    return array_map(function ($item) {
        switch (true) {
            case $item % self::MATCH_FIZZBUZZ === 0:
                return 'FizzBuzz';
            case $item % self::MATCH_FIZZ === 0:
                return 'Fizz';
            case $item % self::MATCH_BUZZ === 0:
                return 'Buzz';
        }

        return $item;
    }, $list);
```

**Comment by settermjd** [comment]
Definitely an interesting discussion. I see the point about cleanliness, and appreciate the PR to bring that about. I'm mixed on multiple return points. I definitely feel that the fewer there are, the better, and that they should, indeed, be used with caution. But I don't believe in a hard and fast rule of one in, one out. 

Borrowing a line from @pmjones:

> There are no solutions only trade offs

So use wise judgement based on your situation. Going further, I don't think this example is sufficient enough to make a call one way or the other. But I like the readability of the revised version. The discussion engages me far more, however. @Jean85, thanks for the link to the talk. Will be checking it out later.

**Comment by rdohms** [comment]
@settermjd the point of the PR was the discussion actually, was not even expecting it to be merged.

The `switch(true)` solution here would work nicely, but there are some who shun it. I see no real issue if its properly used.

As far as OC goes, to me they are guidelines, meaning, break them, but do so for valid reasons and think about what you are doing. There are cases where the else is your best option, there are also very gray areas:

`$var = $x ?? $z;` or `$r = ($condition)? $simple : $simpler;`

These can be very readable for simple conditions and outcomes or be terribly misused and become hell, but they are still `else`implementations.

My goal is always strive for minimum moving pieces, make it as simple as possible. Then you draw your limits as to what you can do to to make it simple. Like how many classes does it take to add two values. 😄

**Comment by settermjd** [comment]
@rdohms thanks for initiating the discussion. I've found it quite enlightening.

**Pull request merged**
